/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/src/lib/utils.ts",
      type: "registry:lib",
    }],
  },
  "use-sound": {
    name: "use-sound",
    description: "Custom React hook to load and play a sound from a given URL using the Web Audio API.",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-sound.ts",
      type: "registry:hook",
    }],
  },
  "shimmering-text": {
    name: "shimmering-text",
    description: "Smooth shimmering text animation built with Motion.",
    type: "registry:component",
    files: [{
      path: "src/registry/shimmering-text/shimmering-text.tsx",
      type: "registry:component",
    }],
  },
  "shimmering-text-demo": {
    name: "shimmering-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/shimmering-text-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/shimmering-text-demo.tsx")),
  },
}